
$('#dropdown li').on('click',function(){
 alert($(this).text());
var city="Taipei";    $.ajax('https://query.yahooapis.com/v1/public/yql', {
         method: 'GET',
         data: {
           q: 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="' + city + '")',
           format: 'json'
         },
         success: function (data) {
          var weatherInfo = data.query.results.channel;
           var tempC = (weatherInfo.item.condition.temp -32)*5/9;
      
$('#temp').text(tempC);
          $('.date').text(weatherInfo.item.condition.date);
           $('.text').text(weatherInfo.item.condition.text); 
$('.fore').text(weatherInfo.item.forecast); 
         
           
           
           
           
         }
       });
  
  });
/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  




